site_name: Citrix XenServer SDK
site_description: Reference guide for Citrix XenServer SDK

theme_dir: theme_multi
#theme: mkdocs
repo_url: https://github.com/ajitchelat/AppDNA-SDK.git
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Welcome: index.md
- connectors_about_co4: connectors_about_co4.md
- connector_config_create_co4: connector_config_create_co4.md
- connector_config_fields3_vs4: connector_config_fields3_vs4.md
- connector_config_fields_ah4: connector_config_fields_ah4.md
- connector_config_fields_ah_mc4: connector_config_fields_ah_mc4.md
- connector_config_fields_az4: connector_config_fields_az4.md
- connector_config_fields_fs4: connector_config_fields_fs4.md
- connector_config_fields_pv4: connector_config_fields_pv4.md
- connector_config_fields_vs_mc4: connector_config_fields_vs_mc4.md
- connector_config_fields_vw4: connector_config_fields_vw4.md
- connector_config_fields_xs4: connector_config_fields_xs4.md
- connector_config_fields_xs_mc4: connector_config_fields_xs_mc4.md
- get_started_deploy_release_notes_co4: get_started_deploy_release_notes_co4.md
- get_started_deploy_unidesk_elm_ah4: get_started_deploy_unidesk_elm_ah4.md
- get_started_deploy_unidesk_elm_az4: get_started_deploy_unidesk_elm_az4.md
- get_started_deploy_unidesk_elm_co4: get_started_deploy_unidesk_elm_co4.md
- get_started_deploy_unidesk_elm_hv4: get_started_deploy_unidesk_elm_hv4.md
- get_started_deploy_unidesk_elm_vs4: get_started_deploy_unidesk_elm_vs4.md
- get_started_deploy_unidesk_elm_xs4: get_started_deploy_unidesk_elm_xs4.md
- get_started_install_agent_pv4: get_started_install_agent_pv4.md
- get_started_license_co4: get_started_license_co4.md
- get_started_login_ah4: get_started_login_ah4.md
- get_started_login_az4: get_started_login_az4.md
- get_started_login_co4: get_started_login_co4.md
- get_started_login_hv4: get_started_login_hv4.md
- get_started_login_vs4: get_started_login_vs4.md
- get_started_login_xs4: get_started_login_xs4.md
- get_started_prerequisites_ah4: get_started_prerequisites_ah4.md
- get_started_prerequisites_az4: get_started_prerequisites_az4.md
- get_started_prerequisites_hv4: get_started_prerequisites_hv4.md
- get_started_prerequisites_vs4: get_started_prerequisites_vs4.md
- get_started_prerequisites_xs4: get_started_prerequisites_xs4.md
- get_started_setup_fileshare_co4: get_started_setup_fileshare_co4.md
- get_started_upgrade_elm_co4: get_started_upgrade_elm_co4.md
- get_started_upgrade_unidesk_co4: get_started_upgrade_unidesk_co4.md
- glossary_co4: glossary_co4.md
- labs_enable_co4: labs_enable_co4.md
- landing_install_ah4: landing_install_ah4.md
- landing_install_az4: landing_install_az4.md
- landing_install_hv4: landing_install_hv4.md
- landing_install_vs4: landing_install_vs4.md
- landing_install_xs4: landing_install_xs4.md
- landing_layer_co4: landing_layer_co4.md
- landing_publish_co4: landing_publish_co4.md
- landing_set_up_co4: landing_set_up_co4.md
- layered_images_co4: layered_images_co4.md
- layered_images_create_template_ah4: layered_images_create_template_ah4.md
- layered_images_create_template_ah_mc4: layered_images_create_template_ah_mc4.md
- layered_images_create_template_az4: layered_images_create_template_az4.md
- layered_images_create_template_co4: layered_images_create_template_co4.md
- layered_images_create_template_fs4: layered_images_create_template_fs4.md
- layered_images_create_template_mc4: layered_images_create_template_mc4.md
- layered_images_create_template_pv4: layered_images_create_template_pv4.md
- layered_images_create_template_vs4: layered_images_create_template_vs4.md
- layered_images_create_template_vw4: layered_images_create_template_vw4.md
- layered_images_create_template_xs4: layered_images_create_template_xs4.md
- layered_images_create_template_xs_mc4: layered_images_create_template_xs_mc4.md
- layered_images_manage_template_co4: layered_images_manage_template_co4.md
- layered_images_publish_ah4: layered_images_publish_ah4.md
- layered_images_publish_ah_mc4: layered_images_publish_ah_mc4.md
- layered_images_publish_az4: layered_images_publish_az4.md
- layered_images_publish_co4: layered_images_publish_co4.md
- layered_images_publish_fs4: layered_images_publish_fs4.md
- layered_images_publish_mc4: layered_images_publish_mc4.md
- layered_images_publish_pv4: layered_images_publish_pv4.md
- layered_images_publish_vs4: layered_images_publish_vs4.md
- layered_images_publish_vw4: layered_images_publish_vw4.md
- layered_images_publish_xs4: layered_images_publish_xs4.md
- layered_images_publish_xs_mc4: layered_images_publish_xs_mc4.md
- layer_about_co4: layer_about_co4.md
- layer_apps_co4: layer_apps_co4.md
- layer_apps_create_ah4: layer_apps_create_ah4.md
- layer_apps_create_az4: layer_apps_create_az4.md
- layer_apps_create_co4: layer_apps_create_co4.md
- layer_apps_create_fs4: layer_apps_create_fs4.md
- layer_apps_create_vs4: layer_apps_create_vs4.md
- layer_apps_create_xs4: layer_apps_create_xs4.md
- layer_apps_delete_co4: layer_apps_delete_co4.md
- layer_apps_recipes_co4: layer_apps_recipes_co4.md
- layer_assign_apps_co4: layer_assign_apps_co4.md
- layer_assign_apps_elastic_co4: layer_assign_apps_elastic_co4.md
- layer_assign_apps_image_template_co4: layer_assign_apps_image_template_co4.md
- layer_delete_co4: layer_delete_co4.md
- layer_os_co4: layer_os_co4.md
- layer_os_create_ah4: layer_os_create_ah4.md
- layer_os_create_az4: layer_os_create_az4.md
- layer_os_create_co4: layer_os_create_co4.md
- layer_os_create_fs4: layer_os_create_fs4.md
- layer_os_create_vs4: layer_os_create_vs4.md
- layer_os_create_xs4: layer_os_create_xs4.md
- layer_os_delete_co4: layer_os_delete_co4.md
- layer_os_image_prep_ah4: layer_os_image_prep_ah4.md
- layer_os_image_prep_az4: layer_os_image_prep_az4.md
- layer_os_image_prep_co4: layer_os_image_prep_co4.md
- layer_os_image_prep_vs4: layer_os_image_prep_vs4.md
- layer_os_image_prep_xs4: layer_os_image_prep_xs4.md
- layer_os_version_ah4: layer_os_version_ah4.md
- layer_os_version_az4: layer_os_version_az4.md
- layer_os_version_co4: layer_os_version_co4.md
- layer_os_version_vs4: layer_os_version_vs4.md
- layer_os_version_xs4: layer_os_version_xs4.md
- layer_platform_create_ah4: layer_platform_create_ah4.md
- layer_platform_create_ah_mc4: layer_platform_create_ah_mc4.md
- layer_platform_create_az4: layer_platform_create_az4.md
- layer_platform_create_co4: layer_platform_create_co4.md
- layer_platform_create_mc4: layer_platform_create_mc4.md
- layer_platform_create_ot4: layer_platform_create_ot4.md
- layer_platform_create_pv4: layer_platform_create_pv4.md
- layer_platform_create_vs4: layer_platform_create_vs4.md
- layer_platform_create_vw4: layer_platform_create_vw4.md
- layer_platform_create_xs4: layer_platform_create_xs4.md
- layer_platform_delete_co4: layer_platform_delete_co4.md
- layer_user_enable_co4: layer_user_enable_co4.md
- logs_export_co4: logs_export_co4.md
- platforms_for_publishing_pb_bk4: platforms_for_publishing_pb_bk4.md
- platforms_for_publishing_pb_hy4: platforms_for_publishing_pb_hy4.md
- platforms_for_publishing_pb_ps4: platforms_for_publishing_pb_ps4.md
- scenarios_ah4: scenarios_ah4.md
- scenarios_az4: scenarios_az4.md
- scenarios_co4: scenarios_co4.md
- scenarios_hv4: scenarios_hv4.md
- scenarios_pv4: scenarios_pv4.md
- scenarios_vw4: scenarios_vw4.md
- scenarios_xa65_pv4: scenarios_xa65_pv4.md
- scenarios_xs4: scenarios_xs4.md
- support_co4: support_co4.md
- system_manage_appliance_co4: system_manage_appliance_co4.md
- system_ports_firewall_co4: system_ports_firewall_co4.md
- system_settings_co4: system_settings_co4.md
- system_storage_co4: system_storage_co4.md
- system_update_license_co4: system_update_license_co4.md
- users_admins_assign_role_co4: users_admins_assign_role_co4.md
- users_admin_password_co4: users_admin_password_co4.md
- users_dir_service_co4: users_dir_service_co4.md
- welcome_platform_support_co4: welcome_platform_support_co4.md
- welcome_release_notes_co4: welcome_release_notes_co4.md